[package]
name = "pixels_slow"
version = "0.1.0"
edition = "2024"

[dependencies]
shared = { path = "../shared" }
pixels = "0.13"
winit = { version = "0.30", features = ["rwh_05"] }
log = "0.4"
env_logger = "0.10"
winit_input_helper = "0.17.0"
mint = "0.5.9"
